/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaproject;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ricar
 */
public class Atencion extends javax.swing.JPanel {

    /**
     * Creates new form panelPersonal
     */
    int[] pos = new int[1];
     boolean[] modo=new boolean[1];
     int u=0;
    public Atencion() {
        initComponents();
        /*mostrardatospanel.setVisible(false);
        setPanelEnabled(signospanel, false);
        setPanelEnabled(evaluacionpanel,false);
        setPanelEnabled(medicamentospanel, false);
        
         */
       
        DefaultTableModel modelo = (DefaultTableModel) citastable.getModel();
        modelo.setRowCount(0);

        for (int i = 0; i < 300; i++) {

            // si no hay cita, no la agregues
            if (interfazOwner.datos_citas[0][i] == null) {
                continue;
            }

            modelo.addRow(new Object[]{
                i,
                interfazOwner.datos_citas[0][i],
                interfazOwner.datos_citas[1][i],
                interfazOwner.datos_citas[2][i] + "0",
                interfazOwner.datos_citas[3][i] + "0",});
        }

        motivotxt.setEditable(false);

        activarpaneles(false);
    }

    private void setPanelEnabled(JPanel panel, boolean enabled) {
        panel.setEnabled(enabled);

        for (Component c : panel.getComponents()) {
            c.setEnabled(enabled);

            if (c instanceof JPanel) {
                setPanelEnabled((JPanel) c, enabled);
            }
        }
    }

    private void activarpaneles(boolean valor) {
        motivotxt.setEnabled(valor);
        diagnosticotxt.setEnabled(valor);
        consideracionestxt.setEnabled(valor);
        //mostrardatospanel.setVisible(valor);
        setPanelEnabled(signospanel, valor);
        setPanelEnabled(evaluacionpanel, valor);
        setPanelEnabled(medicamentospanel, valor);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signospanel = new javax.swing.JPanel();
        tallafield = new javax.swing.JTextField();
        pesofield = new javax.swing.JTextField();
        precionfield = new javax.swing.JTextField();
        frecuenciafield = new javax.swing.JTextField();
        saturacionfield = new javax.swing.JTextField();
        temperaturafield = new javax.swing.JTextField();
        guardardatosbutton = new javax.swing.JButton();
        imclabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        dnifield = new javax.swing.JTextField();
        buscarbutton = new javax.swing.JButton();
        seleccioncombo = new javax.swing.JComboBox<>();
        mostrardatospanel = new javax.swing.JPanel();
        dninombre = new javax.swing.JLabel();
        dnilabel = new javax.swing.JLabel();
        sexolabel = new javax.swing.JLabel();
        edadlabel = new javax.swing.JLabel();
        evaluacionpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        motivotxt = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        diagnosticotxt = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        consideracionestxt = new javax.swing.JTextArea();
        medicamentospanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        borrarbutton = new javax.swing.JButton();
        confirmarbutton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablascroll = new javax.swing.JScrollPane();
        citastable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(840, 520));

        signospanel.setBorder(javax.swing.BorderFactory.createTitledBorder("SIGNOS VITALES"));

        tallafield.setBorder(javax.swing.BorderFactory.createTitledBorder("TALLA (CM)"));
        tallafield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tallafieldActionPerformed(evt);
            }
        });

        pesofield.setBorder(javax.swing.BorderFactory.createTitledBorder("PESO (KG)"));
        pesofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesofieldActionPerformed(evt);
            }
        });

        precionfield.setBorder(javax.swing.BorderFactory.createTitledBorder("PRECION ARTERIAL"));
        precionfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precionfieldActionPerformed(evt);
            }
        });

        frecuenciafield.setBorder(javax.swing.BorderFactory.createTitledBorder("FRECUENCIA CARDIACA"));
        frecuenciafield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frecuenciafieldActionPerformed(evt);
            }
        });

        saturacionfield.setBorder(javax.swing.BorderFactory.createTitledBorder("SATURACION "));
        saturacionfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saturacionfieldActionPerformed(evt);
            }
        });

        temperaturafield.setBorder(javax.swing.BorderFactory.createTitledBorder("TEMPERATURA (C)"));
        temperaturafield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperaturafieldActionPerformed(evt);
            }
        });

        guardardatosbutton.setText("GUARDAR DATOS");
        guardardatosbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardardatosbuttonActionPerformed(evt);
            }
        });

        imclabel.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        imclabel.setBorder(javax.swing.BorderFactory.createTitledBorder("IMC"));

        javax.swing.GroupLayout signospanelLayout = new javax.swing.GroupLayout(signospanel);
        signospanel.setLayout(signospanelLayout);
        signospanelLayout.setHorizontalGroup(
            signospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signospanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(signospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signospanelLayout.createSequentialGroup()
                        .addGroup(signospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(signospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(precionfield, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(tallafield))
                            .addComponent(frecuenciafield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(signospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(saturacionfield)
                            .addComponent(temperaturafield, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(pesofield)))
                    .addComponent(imclabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guardardatosbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        signospanelLayout.setVerticalGroup(
            signospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signospanelLayout.createSequentialGroup()
                .addGroup(signospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tallafield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precionfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temperaturafield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frecuenciafield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saturacionfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imclabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardardatosbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("DATOS DEL PACIENTE"));

        dnifield.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        buscarbutton.setText("BUSCAR");
        buscarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarbuttonActionPerformed(evt);
            }
        });

        seleccioncombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "COLA" }));
        seleccioncombo.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seleccioncombo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dnifield, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarbutton)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(buscarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(seleccioncombo, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(dnifield)))
        );

        dninombre.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        dninombre.setBorder(javax.swing.BorderFactory.createTitledBorder("PACIENTE"));

        dnilabel.setBorder(javax.swing.BorderFactory.createTitledBorder("DNI"));

        sexolabel.setBorder(javax.swing.BorderFactory.createTitledBorder("SEXO"));

        edadlabel.setBorder(javax.swing.BorderFactory.createTitledBorder("EDAD"));

        javax.swing.GroupLayout mostrardatospanelLayout = new javax.swing.GroupLayout(mostrardatospanel);
        mostrardatospanel.setLayout(mostrardatospanelLayout);
        mostrardatospanelLayout.setHorizontalGroup(
            mostrardatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrardatospanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mostrardatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(dninombre, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mostrardatospanelLayout.createSequentialGroup()
                        .addComponent(dnilabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edadlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sexolabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mostrardatospanelLayout.setVerticalGroup(
            mostrardatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mostrardatospanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dninombre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mostrardatospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dnilabel, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(edadlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sexolabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrardatospanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mostrardatospanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        evaluacionpanel.setBorder(javax.swing.BorderFactory.createTitledBorder("EVALUACION"));

        motivotxt.setColumns(20);
        motivotxt.setRows(5);
        motivotxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Motivo"));
        jScrollPane1.setViewportView(motivotxt);

        diagnosticotxt.setColumns(20);
        diagnosticotxt.setRows(5);
        diagnosticotxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Diagnostico"));
        jScrollPane2.setViewportView(diagnosticotxt);

        consideracionestxt.setColumns(20);
        consideracionestxt.setRows(5);
        consideracionestxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Consideraciones"));
        jScrollPane3.setViewportView(consideracionestxt);

        javax.swing.GroupLayout evaluacionpanelLayout = new javax.swing.GroupLayout(evaluacionpanel);
        evaluacionpanel.setLayout(evaluacionpanelLayout);
        evaluacionpanelLayout.setHorizontalGroup(
            evaluacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, evaluacionpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addContainerGap())
        );
        evaluacionpanelLayout.setVerticalGroup(
            evaluacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, evaluacionpanelLayout.createSequentialGroup()
                .addGroup(evaluacionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        medicamentospanel.setBorder(javax.swing.BorderFactory.createTitledBorder("MEDICAMENTOS"));

        jTextField10.setBorder(javax.swing.BorderFactory.createTitledBorder("CODIGO"));

        jButton3.setText("AGREGAR");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinner1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad"));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(375, 375, 375)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout medicamentospanelLayout = new javax.swing.GroupLayout(medicamentospanel);
        medicamentospanel.setLayout(medicamentospanelLayout);
        medicamentospanelLayout.setHorizontalGroup(
            medicamentospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicamentospanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        medicamentospanelLayout.setVerticalGroup(
            medicamentospanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicamentospanelLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        borrarbutton.setText("BORRAR");
        borrarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarbuttonActionPerformed(evt);
            }
        });

        confirmarbutton.setText("CONFIRMAR");
        confirmarbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarbuttonActionPerformed(evt);
            }
        });

        citastable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "COLA", "DNI", "FECHA", "INICIO", "FIN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablascroll.setViewportView(citastable);

        jScrollPane5.setViewportView(tablascroll);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(medicamentospanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(confirmarbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(borrarbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(evaluacionpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(signospanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(signospanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(evaluacionpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(borrarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(confirmarbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(medicamentospanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tallafieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tallafieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tallafieldActionPerformed

    private void pesofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesofieldActionPerformed

    private void frecuenciafieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frecuenciafieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frecuenciafieldActionPerformed

    private void precionfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precionfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precionfieldActionPerformed

    private void saturacionfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saturacionfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saturacionfieldActionPerformed

    private void temperaturafieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperaturafieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temperaturafieldActionPerformed

    private void guardardatosbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardardatosbuttonActionPerformed

        double peso = Double.parseDouble(pesofield.getText());
        double tallaCm = Double.parseDouble(tallafield.getText());
        double tallaM = tallaCm / 100.0;
        double indice = peso / (tallaM * tallaM);
        imclabel.setText(" " + indice);
        interfazOwner.datos_aten[0][u] = dnifield.getText();
        interfazOwner.datos_aten[1][pos[0]] = diagnosticotxt.getText();
        interfazOwner.datos_aten[2][pos[0]] = pesofield.getText();
        interfazOwner.datos_aten[3][pos[0]] = tallafield.getText();
        interfazOwner.datos_aten[4][pos[0]] = temperaturafield.getText();
        interfazOwner.datos_aten[5][pos[0]] = precionfield.getText();
        interfazOwner.datos_aten[6][pos[0]] = frecuenciafield.getText();
        interfazOwner.datos_aten[7][pos[0]] = saturacionfield.getText();
        interfazOwner.datos_aten[8][pos[0]] = String.valueOf(indice);
        u=10;

        setPanelEnabled(signospanel, false);
        signospanel.setBorder(
                javax.swing.BorderFactory.createTitledBorder("SIGNOS VITALES (GUARDADO)")
        );
        /*pesofield.setText("");
        tallafield.setText("");
        temperaturafield.setText("");
        frecuenciafield.setText("");
        precionfield.setText("");
        saturacionfield.setText("");*/

    }//GEN-LAST:event_guardardatosbuttonActionPerformed

    private void confirmarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarbuttonActionPerformed
        interfazOwner.datos_aten[9][pos[0]] = diagnosticotxt.getText();
        interfazOwner.datos_aten[10][pos[0]] = consideracionestxt.getText();
        interfazOwner.datos_aten[11][pos[0]] = interfazOwner.datos_citas[1][pos[0]];
        interfazOwner.datos_aten[12][pos[0]] = interfazOwner.datos_citas[2][pos[0]];
        interfazOwner.datos_aten[13][pos[0]] = interfazOwner.datos_citas[3][pos[0]];
        pos[0]++;
        activarpaneles(false);
    }//GEN-LAST:event_confirmarbuttonActionPerformed

    private void borrarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarbuttonActionPerformed
        dnifield.setText("");
        tallafield.setText("");
        pesofield.setText("");
        temperaturafield.setText("");
        precionfield.setText("");
        frecuenciafield.setText("");
        saturacionfield.setText("");

        motivotxt.setText("");
        diagnosticotxt.setText("");
        consideracionestxt.setText("");

        imclabel.setText("");
        jSpinner1.setValue(0);

        activarpaneles(false);

    }//GEN-LAST:event_borrarbuttonActionPerformed

    private void buscarbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarbuttonActionPerformed
        String valor;
        if (dnifield != null) {
            switch (seleccioncombo.getSelectedIndex()) {
                case 0: valor=dnifield.getText();
                    for (int i = 0; i < 300; i++) {
                        if (interfazOwner.datos_citas[0][i] != null
                                && interfazOwner.datos_citas[0][i].equals(dnifield.getText())) {

                            activarpaneles(true);
                            pos[0] = i;
                            dninombre.setText(interfazOwner.datos_pacien[1][i] + " " + interfazOwner.datos_pacien[2][i] + " " + interfazOwner.datos_pacien[3][i]);
                            dnilabel.setText(interfazOwner.datos_pacien[0][i]);
                            edadlabel.setText(interfazOwner.datos_pacien[5][i]);
                            sexolabel.setText(interfazOwner.datos_pacien[6][i]);
                            motivotxt.setText(interfazOwner.datos_citas[4][pos[0]]);
                            break; //
                        }
                    }

                    break;
                case 1:
                    for (int i = 0; i < 300; i++) {
                        if (interfazOwner.datos_citas[0][i] != null
                                && interfazOwner.datos_citas[0][i].equals(interfazOwner.datos_citas[0][Integer.parseInt(dnifield.getText())])) {
                            valor=interfazOwner.datos_citas[0][Integer.parseInt(dnifield.getText())];
                            
                            activarpaneles(true);
                            pos[0] = i;
                            dninombre.setText(interfazOwner.datos_pacien[1][i] + " " + interfazOwner.datos_pacien[2][i] + " " + interfazOwner.datos_pacien[3][i]);
                            dnilabel.setText(interfazOwner.datos_pacien[0][i]);
                            edadlabel.setText(interfazOwner.datos_pacien[5][i]);
                            sexolabel.setText(interfazOwner.datos_pacien[6][i]);
                            motivotxt.setText(interfazOwner.datos_citas[4][pos[0]]);
                            break; //
                        }
                    }

                default:
                    throw new AssertionError();
            }
            /*for (int i = 0; i < 300; i++) {
                        if (interfazOwner.datos_citas[0][i] != null
                                && interfazOwner.datos_citas[0][i].equals(valor)) {

                            activarpaneles(true);
                            pos[0] = i;
                            dninombre.setText(interfazOwner.datos_pacien[1][i] + " " + interfazOwner.datos_pacien[2][i] + " " + interfazOwner.datos_pacien[3][i]);
                            dnilabel.setText(interfazOwner.datos_pacien[0][i]);
                            edadlabel.setText(interfazOwner.datos_pacien[5][i]);
                            sexolabel.setText(interfazOwner.datos_pacien[6][i]);
                            motivotxt.setText(interfazOwner.datos_citas[4][pos[0]]);
                            break; 
                            
                        }
                    }*/
        }


    }//GEN-LAST:event_buscarbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarbutton;
    private javax.swing.JButton buscarbutton;
    private javax.swing.JTable citastable;
    private javax.swing.JButton confirmarbutton;
    private javax.swing.JTextArea consideracionestxt;
    private javax.swing.JTextArea diagnosticotxt;
    private javax.swing.JTextField dnifield;
    private javax.swing.JLabel dnilabel;
    private javax.swing.JLabel dninombre;
    private javax.swing.JLabel edadlabel;
    private javax.swing.JPanel evaluacionpanel;
    private javax.swing.JTextField frecuenciafield;
    private javax.swing.JButton guardardatosbutton;
    private javax.swing.JLabel imclabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JPanel medicamentospanel;
    private javax.swing.JPanel mostrardatospanel;
    private javax.swing.JTextArea motivotxt;
    private javax.swing.JTextField pesofield;
    private javax.swing.JTextField precionfield;
    private javax.swing.JTextField saturacionfield;
    private javax.swing.JComboBox<String> seleccioncombo;
    private javax.swing.JLabel sexolabel;
    private javax.swing.JPanel signospanel;
    private javax.swing.JScrollPane tablascroll;
    private javax.swing.JTextField tallafield;
    private javax.swing.JTextField temperaturafield;
    // End of variables declaration//GEN-END:variables
}
