package javaproject;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author jaret
 */
public class botica_principal extends javax.swing.JPanel {

    /**
     * Creates new form botica_principal
     */
    public botica_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botica_recojer = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botica_stock = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1360, 718));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botica_recojer.setBackground(new java.awt.Color(10, 60, 100,150));
        botica_recojer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botica_recojerMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Font Awesome 6 Free Solid", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("recojo de medicamantos");

        jLabel8.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("<html><div style=\"width: 200px; text-align: center;\">Recoger medicamentos y descontar del stock</div>");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/images/recojo.png"))); // NOI18N

        javax.swing.GroupLayout botica_recojerLayout = new javax.swing.GroupLayout(botica_recojer);
        botica_recojer.setLayout(botica_recojerLayout);
        botica_recojerLayout.setHorizontalGroup(
            botica_recojerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botica_recojerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(botica_recojerLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel7)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botica_recojerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        botica_recojerLayout.setVerticalGroup(
            botica_recojerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botica_recojerLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(botica_recojer, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 207, 340, 330));

        botica_stock.setBackground(new java.awt.Color(10, 60, 100,150));
        botica_stock.setPreferredSize(new java.awt.Dimension(330, 330));
        botica_stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botica_stockMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Font Awesome 6 Free Solid", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("consultar stock");

        jLabel5.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html><div style=\"width: 200px; text-align: center;\">Ver y agregar stock de medicamentos</div>");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/images/guardar.png"))); // NOI18N

        javax.swing.GroupLayout botica_stockLayout = new javax.swing.GroupLayout(botica_stock);
        botica_stock.setLayout(botica_stockLayout);
        botica_stockLayout.setHorizontalGroup(
            botica_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botica_stockLayout.createSequentialGroup()
                .addGroup(botica_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(botica_stockLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel4))
                    .addGroup(botica_stockLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botica_stockLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(97, 97, 97))
        );
        botica_stockLayout.setVerticalGroup(
            botica_stockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botica_stockLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(botica_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 207, -1, 330));

        jLabel1.setBackground(new java.awt.Color(20, 40, 60));
        jLabel1.setFont(new java.awt.Font("Font Awesome 6 Free Solid", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(44, 62, 80));
        jLabel1.setText("Modulo de botica");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, 105));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/images/fondoHospital.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void botica_recojerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botica_recojerMouseClicked
        // TODO add your handling code here:
        interfazOwner principal = (interfazOwner) javax.swing.SwingUtilities.getWindowAncestor(this);

        principal.cambiarPanel(new recojo_medi());
    }//GEN-LAST:event_botica_recojerMouseClicked

    private void botica_stockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botica_stockMouseClicked
        // TODO add your handling code here:

        interfazOwner principal = (interfazOwner) javax.swing.SwingUtilities.getWindowAncestor(this);

        principal.cambiarPanel(new stock_medi());
    }//GEN-LAST:event_botica_stockMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botica_recojer;
    private javax.swing.JPanel botica_stock;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
