/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaproject;

/**
 *
 * @author Nestor S
 */
public class gestionarCitas extends javax.swing.JPanel {

    /**
     * Creates new form gestionarCitas
     */
    public gestionarCitas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSecundario = new javax.swing.JPanel();
        panelFecha = new javax.swing.JPanel();
        lblDia = new javax.swing.JLabel();
        cboDia_Buscar = new javax.swing.JComboBox<>();
        lblMes = new javax.swing.JLabel();
        cboMes_Buscar = new javax.swing.JComboBox<>();
        lblAnyo = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtListaCitas = new javax.swing.JTextArea();
        btnBorrarCita = new javax.swing.JButton();
        txtPosicion_a_Borrar = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1360, 718));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSecundario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "BUSCAR"));
        panelSecundario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFecha.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDia.setText("DÍA:");

        cboDia_Buscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        lblMes.setText("MES:");

        cboMes_Buscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        lblAnyo.setText("AÑO 2026");

        javax.swing.GroupLayout panelFechaLayout = new javax.swing.GroupLayout(panelFecha);
        panelFecha.setLayout(panelFechaLayout);
        panelFechaLayout.setHorizontalGroup(
            panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboDia_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMes, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboMes_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(lblAnyo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        panelFechaLayout.setVerticalGroup(
            panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDia)
                    .addComponent(cboDia_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMes)
                    .addComponent(cboMes_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnyo))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        panelSecundario.add(panelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 470, 50));

        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("FECHA");
        lblFecha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelSecundario.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 37, 63, -1));

        txtListaCitas.setEditable(false);
        txtListaCitas.setColumns(20);
        txtListaCitas.setRows(5);
        txtListaCitas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(txtListaCitas);

        panelSecundario.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 147, 191, 250));

        btnBorrarCita.setText("Borrar");
        panelSecundario.add(btnBorrarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, 40));

        txtPosicion_a_Borrar.setBorder(javax.swing.BorderFactory.createTitledBorder("Borrar en posición..."));
        panelSecundario.add(txtPosicion_a_Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 145, -1));

        add(panelSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 810, 460));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarCita;
    private javax.swing.JComboBox<String> cboDia_Buscar;
    private javax.swing.JComboBox<String> cboMes_Buscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnyo;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMes;
    private javax.swing.JPanel panelFecha;
    private javax.swing.JPanel panelSecundario;
    private javax.swing.JTextArea txtListaCitas;
    private javax.swing.JTextField txtPosicion_a_Borrar;
    // End of variables declaration//GEN-END:variables
}
