/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaproject;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nestor S
 */
public class gestionarCitas extends javax.swing.JPanel {
    
    String fecha;
    
    public gestionarCitas() {
        initComponents();
        for (int i = 0; i < interfazOwner.indiceCita; i++) {
            addTabla(i);
        }
    }
    public void addTabla(int ind) {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        String fila[] = new String[5]; 
        fila[0] = String.valueOf(ind+1);
        for (int i = 1; i < fila.length; i++) {            
            fila[i] = interfazOwner.datos_citas[i-1][ind];
        }
        modelo.addRow(fila);
    }
    public void borrarDelArray(int cola) {
        int ind = cola - 1;
        
        for (int indice = ind; indice < interfazOwner.indiceCita; indice++) {
            for (int datos = 0; datos < interfazOwner.datos_citas.length; datos++) {
                interfazOwner.datos_citas[datos][indice] = interfazOwner.datos_citas[datos][indice+1];
            }
        }
        for (int datos = 0; datos < interfazOwner.datos_citas.length; datos++) {
            interfazOwner.datos_citas[datos][interfazOwner.indiceCita - 1] = null;
        }
        interfazOwner.indiceCita--;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSecundario = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        btnBorrarCita = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jSpinner1 = new javax.swing.JSpinner();
        btnBuscar = new javax.swing.JButton();
        spinnerFecha = new javax.swing.JSpinner();
        btnMostrarTodo = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1360, 718));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSecundario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "BUSCAR"));
        panelSecundario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("Filtrar por fecha");
        lblFecha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelSecundario.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 100, -1));

        btnBorrarCita.setText("Borrar");
        btnBorrarCita.addActionListener(this::btnBorrarCitaActionPerformed);
        panelSecundario.add(btnBorrarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, -1, 40));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cola", "DNI", "Fecha", "Hora de Inicio", "Hora de Término", "Nombres", "Apellidos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla);

        panelSecundario.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 710, 230));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));
        jSpinner1.setBorder(javax.swing.BorderFactory.createTitledBorder("Borrar en Cola"));
        panelSecundario.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 140, -1));

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);
        panelSecundario.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 90, 40));

        spinnerFecha.setModel(new javax.swing.SpinnerDateModel());
        spinnerFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        spinnerFecha.setEditor(new javax.swing.JSpinner.DateEditor(spinnerFecha, "dd/MM/yyyy"));
        panelSecundario.add(spinnerFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 186, 46));

        btnMostrarTodo.setText("MOSTRAR TODO");
        btnMostrarTodo.addActionListener(this::btnMostrarTodoActionPerformed);
        panelSecundario.add(btnMostrarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 120, 40));

        add(panelSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        modelo.setRowCount(0);
        fecha = ((javax.swing.JSpinner.DateEditor)spinnerFecha.getEditor()).getTextField().getText();
        for (int i = 0; i < interfazOwner.indiceCita; i++) {
        if (interfazOwner.datos_citas[1][i].equals(fecha)) {
            addTabla(i);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        modelo.setRowCount(0);
        for (int i = 0; i < interfazOwner.indiceCita; i++) {
            addTabla(i);
        }
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    private void btnBorrarCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarCitaActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        int colaPosicion = (int) jSpinner1.getValue();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            int colaTabla = Integer.parseInt(modelo.getValueAt(i, 0).toString());

            if (colaTabla == colaPosicion) {
                modelo.removeRow(i);
                borrarDelArray(colaPosicion);
                break;
            }
        }     
        modelo.setRowCount(0);
        for (int i = 0; i < interfazOwner.indiceCita; i++) {
            addTabla(i);
        }
        
        moduloCitas m = (moduloCitas) javax.swing.SwingUtilities.getAncestorOfClass(moduloCitas.class, this);
    
        if (m != null) {
            m.actualizarCitasProximas();
        } else {
            System.out.println("No se encontró el panel moduloCitas");
        }
    }//GEN-LAST:event_btnBorrarCitaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarCita;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JPanel panelSecundario;
    private javax.swing.JSpinner spinnerFecha;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
