/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaproject;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nestor S
 */
public class gestionarCitas extends javax.swing.JPanel {
    
    String fecha;
    
    public gestionarCitas() {
        initComponents();
        for (int i = 0; i < interfazOwner.indiceCita; i++) {
            addTabla(i);
        }
    }
    public void addTabla(int ind) {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        String fila[] = new String[5]; 
        fila[0] = String.valueOf(ind+1);
        for (int i = 1; i < fila.length; i++) {            
            fila[i] = interfazOwner.datos_citas[i-1][ind];
        }
        modelo.addRow(fila);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSecundario = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        btnBorrarCita = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jSpinner1 = new javax.swing.JSpinner();
        btnBuscar = new javax.swing.JButton();
        spinnerFecha = new javax.swing.JSpinner();

        setPreferredSize(new java.awt.Dimension(1360, 718));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSecundario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "BUSCAR"));
        panelSecundario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("FECHA");
        lblFecha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelSecundario.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 63, -1));

        btnBorrarCita.setText("Borrar");
        panelSecundario.add(btnBorrarCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, -1, 40));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cola", "DNI", "Fecha", "Hora de Inicio", "Hora de Término"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla);

        panelSecundario.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 530, 230));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));
        jSpinner1.setBorder(javax.swing.BorderFactory.createTitledBorder("Borrar en posición"));
        panelSecundario.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 140, -1));

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);
        panelSecundario.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 73, 90, 40));

        spinnerFecha.setModel(new javax.swing.SpinnerDateModel());
        spinnerFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        spinnerFecha.setEditor(new javax.swing.JSpinner.DateEditor(spinnerFecha, "dd/MM/yyyy"));
        panelSecundario.add(spinnerFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 186, 46));

        add(panelSecundario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        fecha = ((javax.swing.JSpinner.DateEditor)spinnerFecha.getEditor()).getTextField().getText();
        System.out.println("s:"+fecha);
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrarCita;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JPanel panelSecundario;
    private javax.swing.JSpinner spinnerFecha;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
