/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaproject;

import java.awt.Color;

/**
 *
 * @author andylnx
 */
public class interfazOwner extends javax.swing.JFrame {

final Color azulHover = new Color(153, 204, 255);
final Color colorLetra= new Color(255,255,255);
private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interfazOwner.class.getName());

   public static String[][] datos_pacien= new String[10][100];
   public static String[][] datos_citas = new String[8][300];
   public static String[][] datos_aten = new String[8][300];
   public static int[] num_medi=new int[300];//solo cantidad de medicinas de cada paciente
   public static int[][] ind_medi=new int[20][300];//los indices los los medicamentos de cada paciente
   public static int[][] cant_medi=new int[20][300];//la cantidad de cada medicamento de cada paciente
   public static String[][] datos_medi = new String[6][300];
   public static int indiceCita=0;
   //maximo podrá recetar 20 medicamentos

    public interfazOwner() {
        initComponents();
        setResizable(true);
        setSize(1366, 768);
        db.setVisible(true);

    }
    public void cambiarPanel(javax.swing.JPanel nuevoPanel) {

    spaceDates.removeAll();
    spaceDates.add(nuevoPanel, java.awt.BorderLayout.CENTER);
    spaceDates.revalidate();
    spaceDates.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jpan5 = new javax.swing.JPanel();
        db5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jpan = new javax.swing.JPanel();
        db = new javax.swing.JButton();
        jpan1 = new javax.swing.JPanel();
        db1 = new javax.swing.JButton();
        jpan2 = new javax.swing.JPanel();
        db2 = new javax.swing.JButton();
        jpan3 = new javax.swing.JPanel();
        db3 = new javax.swing.JButton();
        jpan4 = new javax.swing.JPanel();
        db4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        spaceDates = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(20, 20, 40));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel8.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(10, 60, 100));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jpan5.setBackground(new java.awt.Color(10, 60, 100));
        jpan5.setForeground(new java.awt.Color(10, 60, 100));
        jpan5.setLayout(new java.awt.GridLayout(1, 2));

        db5.setBackground(new java.awt.Color(10, 60, 100));
        db5.setFont(new java.awt.Font("JetBrainsMono NF ExtraBold", 1, 14)); // NOI18N
        db5.setForeground(new java.awt.Color(255, 255, 255));
        db5.setText("Salir");
        db5.setBorder(null);
        db5.setContentAreaFilled(false);
        db5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                db5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                db5MouseExited(evt);
            }
        });
        db5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db5ActionPerformed(evt);
            }
        });
        jpan5.add(db5);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/images/cropped_image(1).png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/images/notificacion.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/images/bot-l4d2-removebg-preview(1).png"))); // NOI18N
        jLabel7.setText("LOGO");

        jLabel8.setFont(new java.awt.Font("JetBrainsMono NF ExtraBold", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("C.S Fraternidad");

        jpan.setBackground(new java.awt.Color(10, 60, 100));
        jpan.setForeground(new java.awt.Color(10, 60, 100));
        jpan.setLayout(new java.awt.GridLayout(1, 2));

        db.setBackground(new java.awt.Color(10, 60, 100));
        db.setFont(new java.awt.Font("JetBrainsMono NF ExtraBold", 1, 14)); // NOI18N
        db.setForeground(new java.awt.Color(255, 255, 255));
        db.setBorder(null);
        db.setContentAreaFilled(false);
        db.setLabel("Pacientes");
        db.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dbMouseExited(evt);
            }
        });
        db.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbActionPerformed(evt);
            }
        });
        jpan.add(db);

        jpan1.setBackground(new java.awt.Color(10, 60, 100));
        jpan1.setForeground(new java.awt.Color(10, 60, 100));
        jpan1.setLayout(new java.awt.GridLayout(1, 2));

        db1.setBackground(new java.awt.Color(10, 60, 100));
        db1.setFont(new java.awt.Font("JetBrainsMono NF ExtraBold", 1, 14)); // NOI18N
        db1.setForeground(new java.awt.Color(255, 255, 255));
        db1.setText("Citas");
        db1.setBorder(null);
        db1.setContentAreaFilled(false);
        db1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                db1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                db1MouseExited(evt);
            }
        });
        db1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db1ActionPerformed(evt);
            }
        });
        jpan1.add(db1);

        jpan2.setBackground(new java.awt.Color(10, 60, 100));
        jpan2.setForeground(new java.awt.Color(10, 60, 100));
        jpan2.setLayout(new java.awt.GridLayout(1, 2));

        db2.setBackground(new java.awt.Color(10, 60, 100));
        db2.setFont(new java.awt.Font("JetBrainsMono NF ExtraBold", 1, 14)); // NOI18N
        db2.setForeground(new java.awt.Color(255, 255, 255));
        db2.setText("Atenciones");
        db2.setBorder(null);
        db2.setContentAreaFilled(false);
        db2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                db2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                db2MouseExited(evt);
            }
        });
        db2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db2ActionPerformed(evt);
            }
        });
        jpan2.add(db2);

        jpan3.setBackground(new java.awt.Color(10, 60, 100));
        jpan3.setForeground(new java.awt.Color(10, 60, 100));
        jpan3.setLayout(new java.awt.GridLayout(1, 2));

        db3.setBackground(new java.awt.Color(10, 60, 100));
        db3.setFont(new java.awt.Font("JetBrainsMono NF ExtraBold", 1, 14)); // NOI18N
        db3.setForeground(new java.awt.Color(255, 255, 255));
        db3.setText("Botica");
        db3.setBorder(null);
        db3.setContentAreaFilled(false);
        db3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                db3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                db3MouseExited(evt);
            }
        });
        db3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db3ActionPerformed(evt);
            }
        });
        jpan3.add(db3);

        jpan4.setBackground(new java.awt.Color(10, 60, 100));
        jpan4.setForeground(new java.awt.Color(10, 60, 100));
        jpan4.setLayout(new java.awt.GridLayout(1, 2));

        db4.setBackground(new java.awt.Color(10, 60, 100));
        db4.setFont(new java.awt.Font("JetBrainsMono NF ExtraBold", 1, 14)); // NOI18N
        db4.setForeground(new java.awt.Color(255, 255, 255));
        db4.setText("Personal");
        db4.setBorder(null);
        db4.setContentAreaFilled(false);
        db4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                db4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                db4MouseExited(evt);
            }
        });
        db4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                db4ActionPerformed(evt);
            }
        });
        jpan4.add(db4);

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(759, 759, 759))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(26, 26, 26)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                        .addComponent(jpan, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpan2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpan3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpan4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(328, 328, 328)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpan5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jpan5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jSeparator2))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jpan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jpan2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jpan3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jpan4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel5)
                                .addComponent(jSeparator1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 50));

        spaceDates.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        spaceDates.setForeground(new java.awt.Color(255, 255, 255));
        spaceDates.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(236, 242, 246));

        jLabel2.setFont(new java.awt.Font("Font Awesome 6 Free Solid", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(44, 62, 80));
        jLabel2.setText("Posta Fraternidad");

        jLabel1.setForeground(new java.awt.Color(44, 62, 80));
        jLabel1.setText("<html><h2>Bienvenidos al sistema de gestión del C.S. Fraternidad. Nos dedicamos a brindar atención primaria de calidad a nuestra comunidad ucayalina. A través de esta plataforma, centralizamos el cuidado de nuestros Pacientes, agilizamos la programación de Citas y optimizamos el registro de Atenciones diarias. Gestionamos con transparencia nuestra Botica para asegurar el abastecimiento oportuno y contamos con un módulo de Personal para coordinar al equipo humano que vela por tu salud. Tecnología y vocación de servicio, unidas por el bienestar de Fraternidad </h2> ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(224, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(433, 433, 433))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1015, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel2)
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        spaceDates.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel8.add(spaceDates, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1360, 700));

        getContentPane().add(jPanel8, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbActionPerformed
        cambiarPanel(new Pacientes_Menu());

    }//GEN-LAST:event_dbActionPerformed

    private void dbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbMouseEntered
        // TODO add your handling code here:
        db.setForeground(azulHover);
        jpan.setBorder(new javax.swing.border.MatteBorder(0, 0, 2, 0, azulHover));
    }//GEN-LAST:event_dbMouseEntered

    private void dbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbMouseExited
        // TODO add your handling code here:
        db.setForeground(colorLetra);
        jpan.setBorder(new javax.swing.border.MatteBorder(0, 0, 0, 0, java.awt.Color.BLACK));
    }//GEN-LAST:event_dbMouseExited

    private void db1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_db1MouseEntered
        // TODO add your handling code here:
        db1.setForeground(azulHover);
        jpan1.setBorder(new javax.swing.border.MatteBorder(0, 0, 2, 0, azulHover));
    }//GEN-LAST:event_db1MouseEntered

    private void db1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_db1MouseExited
        // TODO add your handling code here:
        db1.setForeground(colorLetra);
        jpan1.setBorder(new javax.swing.border.MatteBorder(0, 0, 0, 0, java.awt.Color.BLACK));
    }//GEN-LAST:event_db1MouseExited

    private void db1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db1ActionPerformed
        
        cambiarPanel(new moduloCitas());


    }//GEN-LAST:event_db1ActionPerformed

    private void db2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_db2MouseEntered
        // TODO add your handling code here:
        db2.setForeground(azulHover);
        jpan2.setBorder(new javax.swing.border.MatteBorder(0, 0, 2, 0, azulHover));
    }//GEN-LAST:event_db2MouseEntered

    private void db2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_db2MouseExited
        // TODO add your handling code here:
        db2.setForeground(colorLetra);
        jpan2.setBorder(new javax.swing.border.MatteBorder(0, 0, 0, 0, java.awt.Color.BLACK));
    }//GEN-LAST:event_db2MouseExited

    private void db2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db2ActionPerformed
        cambiarPanel(new seleccion());


    }//GEN-LAST:event_db2ActionPerformed

    private void db3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_db3MouseEntered
        // TODO add your handling code here:
        db3.setForeground(azulHover);
        jpan3.setBorder(new javax.swing.border.MatteBorder(0, 0, 2, 0, azulHover));
    }//GEN-LAST:event_db3MouseEntered

    private void db3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_db3MouseExited
        // TODO add your handling code here:
        db3.setForeground(colorLetra);
        jpan3.setBorder(new javax.swing.border.MatteBorder(0, 0, 0, 0, java.awt.Color.BLACK));
    }//GEN-LAST:event_db3MouseExited

    private void db3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db3ActionPerformed

        cambiarPanel(new botica_principal());
    }//GEN-LAST:event_db3ActionPerformed

    private void db4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_db4MouseEntered
        // TODO add your handling code here:
        db4.setForeground(azulHover);
        jpan4.setBorder(new javax.swing.border.MatteBorder(0, 0, 2, 0, azulHover));
    }//GEN-LAST:event_db4MouseEntered

    private void db4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_db4MouseExited
        // TODO add your handling code here:
        db4.setForeground(colorLetra);
        jpan4.setBorder(new javax.swing.border.MatteBorder(0, 0, 0, 0, java.awt.Color.BLACK));
    }//GEN-LAST:event_db4MouseExited

    private void db4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db4ActionPerformed

    }//GEN-LAST:event_db4ActionPerformed

    private void db5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_db5MouseEntered
        // TODO add your handling code here:
        db5.setForeground(azulHover);
        jpan5.setBorder(new javax.swing.border.MatteBorder(0, 0, 2, 0, azulHover));
    }//GEN-LAST:event_db5MouseEntered

    private void db5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_db5MouseExited
        // TODO add your handling code here:
        db5.setForeground(colorLetra);
        jpan5.setBorder(new javax.swing.border.MatteBorder(0, 0, 0, 0, java.awt.Color.BLACK));
    }//GEN-LAST:event_db5MouseExited

    private void db5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_db5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_db5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interfazOwner().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton db;
    private javax.swing.JButton db1;
    private javax.swing.JButton db2;
    private javax.swing.JButton db3;
    private javax.swing.JButton db4;
    private javax.swing.JButton db5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpan;
    private javax.swing.JPanel jpan1;
    private javax.swing.JPanel jpan2;
    private javax.swing.JPanel jpan3;
    private javax.swing.JPanel jpan4;
    private javax.swing.JPanel jpan5;
    public static javax.swing.JPanel spaceDates;
    // End of variables declaration//GEN-END:variables
}
