/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaproject;
import javax.swing.JOptionPane;
/**
 *
 * @author andylnx
 */
public class login extends javax.swing.JPanel {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        login_usuario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        login_contraseña = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        verContraseña = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(40,110,160,100));
        jPanel1.setPreferredSize(new java.awt.Dimension(420, 580));

        login_usuario.setBorder(null);

        jButton1.setBackground(new java.awt.Color(40, 110, 160));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INGRESAR");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("FreeMono", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario/DNI");

        jLabel2.setFont(new java.awt.Font("FreeMono", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña");

        login_contraseña.setBorder(null);

        jLabel3.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("POSTA DE FRATERNIDAD - ACCESO");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/images/loginlogo.png"))); // NOI18N

        verContraseña.setBackground(new java.awt.Color(255, 102, 102,0));
        verContraseña.setFont(new java.awt.Font("FreeMono", 2, 12)); // NOI18N
        verContraseña.setForeground(new java.awt.Color(255, 255, 255));
        verContraseña.setText("Ver Contraseña");
        verContraseña.setOpaque(true);
        verContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                verContraseñaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                verContraseñaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verContraseñaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                verContraseñaMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(verContraseña)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(login_contraseña)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(login_usuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addComponent(login_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addComponent(login_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verContraseña)
                .addGap(43, 43, 43)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 94, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/images/renderizacion-del-retrato-del-medico-del-anime.jpg"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    String name ="andy";
     String pass ="123andy";
    interfazOwner principal = (interfazOwner) javax.swing.SwingUtilities.getWindowAncestor(this);
    String temp = login_usuario.getText();
    String temp2 = String.valueOf(login_contraseña.getPassword());
    if(name.equals(temp) && pass.equals(temp2)){
    principal.loginpanel.setVisible(false);
    principal.barraPanel.setVisible(true);
    }else{
            JOptionPane.showMessageDialog(this, "Contraseña incorrecta", "Error", JOptionPane.ERROR_MESSAGE);
            limpiarFormulario();
    }

    }//GEN-LAST:event_jButton1ActionPerformed
    public void limpiarFormulario(){
        login_contraseña.setText("");
        login_usuario.setText("");
    }
    private void verContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verContraseñaMousePressed
        // TODO add your handling code here:
        login_contraseña.setEchoChar((char) 0);
    }//GEN-LAST:event_verContraseñaMousePressed

    private void verContraseñaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verContraseñaMouseEntered
        // TODO add your handling code here:
       
        verContraseña.setForeground(new java.awt.Color(0,0,0));
      
    }//GEN-LAST:event_verContraseñaMouseEntered

    private void verContraseñaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verContraseñaMouseExited
        // TODO add your handling code here:
        verContraseña.setForeground(new java.awt.Color(225,225,225));
     
    }//GEN-LAST:event_verContraseñaMouseExited

    private void verContraseñaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verContraseñaMouseReleased
        // TODO add your handling code here:
         login_contraseña.setEchoChar('*');
    }//GEN-LAST:event_verContraseñaMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField login_contraseña;
    private javax.swing.JTextField login_usuario;
    private javax.swing.JLabel verContraseña;
    // End of variables declaration//GEN-END:variables
}
