package javaproject;

import static javaproject.interfazOwner.spaceDates;

public class moduloCitas extends javax.swing.JPanel {

    
    public moduloCitas() {
        initComponents();     
    }
    public void cambiarPanel(javax.swing.JPanel nuevoPanel) {
        CitasOpciones.removeAll();
        CitasOpciones.add(nuevoPanel, java.awt.BorderLayout.CENTER);
        CitasOpciones.revalidate();
        CitasOpciones.repaint();
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblModuloCitas = new javax.swing.JLabel();
        btnGestionarCitas = new javax.swing.JButton();
        btnNuevaCita = new javax.swing.JButton();
        citas = new javax.swing.JPanel();
        CitasOpciones = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCitasProximasLista = new javax.swing.JTextArea();
        fondo = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1370, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblModuloCitas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblModuloCitas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblModuloCitas.setText("MODULO DE CITAS");
        lblModuloCitas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblModuloCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblModuloCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 22, -1, -1));

        btnGestionarCitas.setText("Gestionar citas");
        btnGestionarCitas.addActionListener(this::btnGestionarCitasActionPerformed);
        add(btnGestionarCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 219, 167, 54));

        btnNuevaCita.setText("Nueva cita");
        btnNuevaCita.addActionListener(this::btnNuevaCitaActionPerformed);
        add(btnNuevaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 136, 167, 54));

        CitasOpciones.setPreferredSize(new java.awt.Dimension(977, 625));
        CitasOpciones.setLayout(new java.awt.GridLayout(1, 1));

        javax.swing.GroupLayout citasLayout = new javax.swing.GroupLayout(citas);
        citas.setLayout(citasLayout);
        citasLayout.setHorizontalGroup(
            citasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(citasLayout.createSequentialGroup()
                .addComponent(CitasOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        citasLayout.setVerticalGroup(
            citasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(citasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CitasOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(citas, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 22, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Próximas citas"));

        txtCitasProximasLista.setEditable(false);
        txtCitasProximasLista.setColumns(20);
        txtCitasProximasLista.setRows(5);
        jScrollPane2.setViewportView(txtCitasProximasLista);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 299, 230, 257));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/images/fondoHospital.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaCitaActionPerformed
        // TODO add your handling code here:      
        cambiarPanel(new nuevaCita());      
    }//GEN-LAST:event_btnNuevaCitaActionPerformed

    private void btnGestionarCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarCitasActionPerformed

        cambiarPanel(new gestionarCitas());      
    }//GEN-LAST:event_btnGestionarCitasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CitasOpciones;
    private javax.swing.JButton btnGestionarCitas;
    private javax.swing.JButton btnNuevaCita;
    private javax.swing.JPanel citas;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblModuloCitas;
    private javax.swing.JTextArea txtCitasProximasLista;
    // End of variables declaration//GEN-END:variables
}
