/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaproject;

/**
 *
 * @author andylnx
 */
public class Pacientes_Menu extends javax.swing.JPanel {


    public Pacientes_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        mRegistrar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mVE = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Font Awesome 6 Free Solid", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(44, 62, 80));
        jLabel1.setText("Gestion de pacientes");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 63, -1, 105));

        mRegistrar.setBackground(new java.awt.Color(40, 110, 160));
        mRegistrar.setPreferredSize(new java.awt.Dimension(330, 330));
        mRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mRegistrarMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/images/agregaruser.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Font Awesome 6 Free Solid", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registrar Nuevo");

        jLabel5.setFont(new java.awt.Font("FreeMono", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html><h3>ingrese datos de personas que nunca se atendieron en esta posta</h3>");

        javax.swing.GroupLayout mRegistrarLayout = new javax.swing.GroupLayout(mRegistrar);
        mRegistrar.setLayout(mRegistrarLayout);
        mRegistrarLayout.setHorizontalGroup(
            mRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mRegistrarLayout.createSequentialGroup()
                .addGroup(mRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mRegistrarLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel3))
                    .addGroup(mRegistrarLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel4))
                    .addGroup(mRegistrarLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94))
        );
        mRegistrarLayout.setVerticalGroup(
            mRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mRegistrarLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(mRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 207, -1, -1));

        jLabel2.setFont(new java.awt.Font("Font Awesome 6 Free Solid", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(44, 62, 80));
        jLabel2.setText("posta de fraternidad");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(561, 174, -1, -1));

        mVE.setBackground(new java.awt.Color(40, 110, 160));
        mVE.setPreferredSize(new java.awt.Dimension(330, 330));
        mVE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mVEMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Font Awesome 6 Free Solid", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ver o Editar");

        jLabel8.setFont(new java.awt.Font("FreeMono", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("<html><h3>ingrese datos de personas que nunca se atendieron en esta posta</h3>");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/images/carpet.png"))); // NOI18N

        javax.swing.GroupLayout mVELayout = new javax.swing.GroupLayout(mVE);
        mVE.setLayout(mVELayout);
        mVELayout.setHorizontalGroup(
            mVELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mVELayout.createSequentialGroup()
                .addGroup(mVELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mVELayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel6))
                    .addGroup(mVELayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel7))
                    .addGroup(mVELayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(105, 105, 105))
        );
        mVELayout.setVerticalGroup(
            mVELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mVELayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(mVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 207, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/images/fondo(1).png"))); // NOI18N
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void mRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mRegistrarMouseClicked
        // TODO add your handling code here:

        interfazOwner principal = (interfazOwner) javax.swing.SwingUtilities.getWindowAncestor(this);

        principal.cambiarPanel(new Pacientes_RegistrarPaciente());
    }//GEN-LAST:event_mRegistrarMouseClicked

    private void mVEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mVEMouseClicked
        // TODO add your handling code here:
        interfazOwner principal = (interfazOwner) javax.swing.SwingUtilities.getWindowAncestor(this);

        principal.cambiarPanel(new Pacientes_VerEditar());
    }//GEN-LAST:event_mVEMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel mRegistrar;
    private javax.swing.JPanel mVE;
    // End of variables declaration//GEN-END:variables
}
