/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaproject;

/**
 *
 * @author andylnx
 */
public class Pacientes_Menu extends javax.swing.JPanel {


    public Pacientes_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mRegistrar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mVE = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fondos = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(20, 40, 60));
        jLabel1.setFont(new java.awt.Font("Font Awesome 6 Free Solid", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(44, 62, 80));
        jLabel1.setText("GestiÓÓÓon de pacientes");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 63, -1, 105));

        jLabel2.setBackground(new java.awt.Color(20, 40, 60));
        jLabel2.setFont(new java.awt.Font("Font Awesome 6 Free Solid", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(44, 62, 80));
        jLabel2.setText("posta de fraternidad");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, -1, -1));

        mRegistrar.setBackground(new java.awt.Color(10, 60, 100,150));
        mRegistrar.setPreferredSize(new java.awt.Dimension(330, 330));
        mRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mRegistrarMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/images/agregar.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Font Awesome 6 Free Solid", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nuevo REGISTRO");

        jLabel8.setFont(new java.awt.Font("Font Awesome 6 Free Solid", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("<html> <div style=\"width: 200px; text-align: center;\"> Registra un nuevo paciente en el sistema. </div> </html>");

        javax.swing.GroupLayout mRegistrarLayout = new javax.swing.GroupLayout(mRegistrar);
        mRegistrar.setLayout(mRegistrarLayout);
        mRegistrarLayout.setHorizontalGroup(
            mRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mRegistrarLayout.createSequentialGroup()
                .addGroup(mRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mRegistrarLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel3))
                    .addGroup(mRegistrarLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel4))
                    .addGroup(mRegistrarLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        mRegistrarLayout.setVerticalGroup(
            mRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mRegistrarLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addGap(50, 50, 50)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(mRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 207, -1, 330));

        mVE.setBackground(new java.awt.Color(10, 60, 100,150));
        mVE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mVEMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Font Awesome 6 Free Solid", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ver o Editar");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/images/guardar.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Font Awesome 6 Free Solid", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("<html> <div style=\"width: 200px; text-align: center;\"> Busca, visualiza y actualiza los datos del paciente. </div> </html>");

        javax.swing.GroupLayout mVELayout = new javax.swing.GroupLayout(mVE);
        mVE.setLayout(mVELayout);
        mVELayout.setHorizontalGroup(
            mVELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mVELayout.createSequentialGroup()
                .addGroup(mVELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mVELayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(mVELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)))
                    .addGroup(mVELayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(240, 240, 240))
        );
        mVELayout.setVerticalGroup(
            mVELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mVELayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(50, 50, 50)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel5.getAccessibleContext().setAccessibleName("Busca, visualiza y actualiza los datos del paciente.");

        add(mVE, new org.netbeans.lib.awtextra.AbsoluteConstraints(776, 207, 340, 330));

        fondos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/images/fondoHospital.png"))); // NOI18N
        add(fondos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void mRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mRegistrarMouseClicked
        // TODO add your handling code here:

        interfazOwner principal = (interfazOwner) javax.swing.SwingUtilities.getWindowAncestor(this);

        principal.cambiarPanel(new Pacientes_RegistrarPaciente());
    }//GEN-LAST:event_mRegistrarMouseClicked

    private void mVEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mVEMouseClicked
        // TODO add your handling code here:
        interfazOwner principal = (interfazOwner) javax.swing.SwingUtilities.getWindowAncestor(this);

        principal.cambiarPanel(new Pacientes_VerEditar());
    }//GEN-LAST:event_mVEMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel mRegistrar;
    private javax.swing.JPanel mVE;
    // End of variables declaration//GEN-END:variables
}
