/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaproject;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricar
 */
public class seleccion extends javax.swing.JPanel {

    /**
     * Creates new form listacitas
     */
    int z=0;
    public seleccion() {
        initComponents();
        añadirbutton.setEnabled(false);
        guardaryvolver.setEnabled(false);
        cantidadspinner.setEnabled(false);
    DefaultTableModel modelo = (DefaultTableModel) listamedicamentos.getModel();
modelo.setRowCount(0); // limpiar tabla
    int i=1;
    for (int x = 0; x < interfazOwner.datos_medi[0].length; x++) {
        
    // si no hay nombre, no existe registro
    if (interfazOwner.datos_medi[0][x] == null) {
        break;
        
    }

    modelo.addRow(new Object[]{
        i,//codigo
        interfazOwner.datos_medi[0][x],//nombre
        interfazOwner.datos_medi[1][x],//dosis
        interfazOwner.datos_medi[2][x],//marca
        interfazOwner.datos_medi[3][x],
        interfazOwner.datos_medi2[0][x],
        interfazOwner.datos_medi2[1][x]
    });
    i++;
}

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txbusc = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        atencionpanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listamedicamentos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        buscador = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        codigofield = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recetatable = new javax.swing.JTable();
        guardaryvolver = new javax.swing.JButton();
        descartar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        añadirbutton = new javax.swing.JButton();
        cantidadspinner = new javax.swing.JSpinner();
        medicamentolabel = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(236, 242, 246));

        jLabel7.setForeground(new java.awt.Color(44, 62, 80));
        jLabel7.setText("Ingrese codigo para editar");
        jPanel1.add(jLabel7);
        jPanel1.add(jSeparator2);

        txbusc.setBackground(new java.awt.Color(236, 242, 246));
        txbusc.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(150, 185, 210)));
        txbusc.setPreferredSize(new java.awt.Dimension(100, 22));
        txbusc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbuscActionPerformed(evt);
            }
        });
        jPanel1.add(txbusc);

        jButton3.setBackground(new java.awt.Color(40, 110, 160));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Seleccionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jPanel1.add(jSeparator3);
        jPanel1.add(jSeparator4);

        jScrollPane4.setPreferredSize(new java.awt.Dimension(670, 50));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Dosis", "Marca", "Vencimiento", "Cantidad", "Alerta de stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable2);

        jPanel1.add(jScrollPane4);

        jButton2.setBackground(new java.awt.Color(40, 110, 160));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("EDITAR");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton1.setBackground(new java.awt.Color(40, 110, 160));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        setLayout(new java.awt.BorderLayout());

        atencionpanel.setBorder(javax.swing.BorderFactory.createTitledBorder("LISTA DE MEDICAMENTOS"));

        listamedicamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Dosis", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(listamedicamentos);

        buscador.setBackground(new java.awt.Color(236, 242, 246));

        jLabel8.setForeground(new java.awt.Color(44, 62, 80));
        jLabel8.setText("INGRESE CODIGO PARA AGREGAR");

        codigofield.setBackground(new java.awt.Color(236, 242, 246));
        codigofield.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(150, 185, 210)));
        codigofield.setPreferredSize(new java.awt.Dimension(100, 22));
        codigofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigofieldActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(40, 110, 160));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Seleccionar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jScrollPane5.setPreferredSize(new java.awt.Dimension(670, 50));

        jTable3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Dosis", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable3);

        javax.swing.GroupLayout buscadorLayout = new javax.swing.GroupLayout(buscador);
        buscador.setLayout(buscadorLayout);
        buscadorLayout.setHorizontalGroup(
            buscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscadorLayout.createSequentialGroup()
                .addGroup(buscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buscadorLayout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel8)
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(codigofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jButton4)
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buscadorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buscadorLayout.setVerticalGroup(
            buscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buscadorLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(buscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buscadorLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addGroup(buscadorLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(codigofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addGroup(buscadorLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("RECETA"));

        recetatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Dosis", "Marca", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        recetatable.setToolTipText("");
        jScrollPane1.setViewportView(recetatable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        guardaryvolver.setText("GUARDAR Y VOLVER");
        guardaryvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardaryvolverActionPerformed(evt);
            }
        });

        descartar.setText("DESCARTAR Y VOLVER");
        descartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descartarActionPerformed(evt);
            }
        });

        añadirbutton.setBackground(new java.awt.Color(40, 110, 160));
        añadirbutton.setForeground(new java.awt.Color(255, 255, 255));
        añadirbutton.setText("AÑADIR");
        añadirbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirbuttonActionPerformed(evt);
            }
        });

        cantidadspinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        cantidadspinner.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad"));

        medicamentolabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Medicamento"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(medicamentolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cantidadspinner, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(añadirbutton)
                .addGap(114, 114, 114))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(medicamentolabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cantidadspinner)
                        .addContainerGap(8, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(añadirbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(descartar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(guardaryvolver))
                            .addComponent(buscador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardaryvolver)
                    .addComponent(descartar)))
        );

        javax.swing.GroupLayout atencionpanelLayout = new javax.swing.GroupLayout(atencionpanel);
        atencionpanel.setLayout(atencionpanelLayout);
        atencionpanelLayout.setHorizontalGroup(
            atencionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atencionpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        atencionpanelLayout.setVerticalGroup(
            atencionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, atencionpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(atencionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(atencionpanel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void txbuscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbuscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbuscActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        interfazOwner principal = (interfazOwner) javax.swing.SwingUtilities.getWindowAncestor(this);
        principal.cambiarPanel(new botica_principal());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void codigofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigofieldActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        String texto = codigofield.getText().trim();

    if (texto.isEmpty()) {
        return;
    }

    int codigo = Integer.parseInt(texto);
    int indice = codigo - 1; // 🔑 conversión

    // validar rango
    if (indice < 0 || indice >= interfazOwner.datos_medi[0].length) {
        return;
    }

    // validar existencia real
    if (interfazOwner.datos_medi[0][indice] == null) {
        return;
    }

    // cargar SOLO el encontrado
    añadirbutton.setEnabled(true);
    cantidadspinner.setEnabled(true);
    DefaultTableModel modelo = (DefaultTableModel) jTable3.getModel();
    modelo.setRowCount(0);

    modelo.addRow(new Object[]{
        codigo,//codigo
        interfazOwner.datos_medi[0][indice], // nombre
        interfazOwner.datos_medi[1][indice], // dosis
        interfazOwner.datos_medi[2][indice], // Marca
        
    });
    medicamentolabel.setText(interfazOwner.datos_medi[0][indice]);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void añadirbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirbuttonActionPerformed
        guardaryvolver.setEnabled(true);
        String colaStr = jTable3.getValueAt(0, 0).toString();
    int cola = Integer.parseInt(colaStr);
        interfazOwner.num_medi[interfazOwner.indiceatencion]++;
        interfazOwner.ind_medi[z][interfazOwner.indiceatencion]=(int)cola;
        interfazOwner.cant_medi[z][interfazOwner.indiceatencion]=(int)cantidadspinner.getValue();
        System.out.println("\nNumero de medicinas num_medi["+interfazOwner.indiceatencion+"]:"+ interfazOwner.num_medi[interfazOwner.indiceatencion]);
        System.out.println("Indices Ind_medi ["+z+"] ["+interfazOwner.indiceatencion+"]:"+cola);
        System.out.println(" Cantidad cant_medi ["+z+"] ["+interfazOwner.indiceatencion+"]:"+(int)cantidadspinner.getValue());
        z++;
        if (jTable3.getRowCount() == 0) {
        return;
    }

    DefaultTableModel modeloReceta =
            (DefaultTableModel) recetatable.getModel();

    Object codigo = jTable3.getValueAt(0, 0);
    Object nombre = jTable3.getValueAt(0, 1);
    Object dosis  = jTable3.getValueAt(0, 2);
    Object marca  = jTable3.getValueAt(0, 3);
    Object cant   = cantidadspinner.getValue();


    modeloReceta.addRow(new Object[]{
        codigo, nombre, dosis, marca, cant
    });

        /*DefaultTableModel modelo = (DefaultTableModel) recetatable.getModel();
modelo.setRowCount(0); // limpiar tabla
    for (int x = 0; x <z; x++) {
        
    // si no hay nombre, no existe registro
    if (interfazOwner.datos_medi[0][x] == null) {
        break;
        
    }

    modelo.addRow(new Object[]{
        cola,//codigo
        interfazOwner.datos_medi[0][x],//nombre
        interfazOwner.datos_medi[1][x],//dosis
        interfazOwner.datos_medi[2][x],//marca
        interfazOwner.datos_medi[4][x],
        interfazOwner.datos_medi2[0][x],
        interfazOwner.datos_medi2[1][x]
    });
}*/
        
    }//GEN-LAST:event_añadirbuttonActionPerformed

    private void descartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descartarActionPerformed
        interfazOwner principal = (interfazOwner) javax.swing.SwingUtilities.getWindowAncestor(this);
        principal.cambiarPanel(new Atencion());
     
        
        
        
    }//GEN-LAST:event_descartarActionPerformed

    private void guardaryvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardaryvolverActionPerformed
       interfazOwner principal = (interfazOwner) javax.swing.SwingUtilities.getWindowAncestor(this);
        principal.cambiarPanel(new Atencion());
        
    }//GEN-LAST:event_guardaryvolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel atencionpanel;
    private javax.swing.JButton añadirbutton;
    private javax.swing.JPanel buscador;
    private javax.swing.JSpinner cantidadspinner;
    private javax.swing.JTextField codigofield;
    private javax.swing.JButton descartar;
    private javax.swing.JButton guardaryvolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable listamedicamentos;
    private javax.swing.JLabel medicamentolabel;
    private javax.swing.JTable recetatable;
    private javax.swing.JTextField txbusc;
    // End of variables declaration//GEN-END:variables
}
