/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaproject;

/**
 *
 * @author ricar
 */
public class seleccion extends javax.swing.JPanel {

    /**
     * Creates new form listacitas
     */
    public seleccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atencionpanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textodebug = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1360, 718));
        setLayout(new java.awt.BorderLayout());

        atencionpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(10, 60, 100));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ATENCION");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        atencionpanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 230, 335, 100));

        jButton2.setBackground(new java.awt.Color(10, 60, 100));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("VER LISTA / DEBUG");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        atencionpanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 382, 335, 100));

        textodebug.setColumns(20);
        textodebug.setRows(5);
        jScrollPane1.setViewportView(textodebug);

        atencionpanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 650, 658));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject/images/fondoHospital.png"))); // NOI18N
        atencionpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 720));

        add(atencionpanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

          interfazOwner principal = (interfazOwner) javax.swing.SwingUtilities.getWindowAncestor(this);    
    principal.cambiarPanel(new Atencion());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        textodebug.setText(interfazOwner.datos_aten[0][0]);
        for (int i = 1; i < 11; i++) {
            textodebug.append(" "+interfazOwner.datos_aten[i][0]);
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel atencionpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textodebug;
    // End of variables declaration//GEN-END:variables
}
