/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaproject;

import javaproject.interfazOwner;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jaret
 */
public class stock_medi extends javax.swing.JPanel {

    /**
     * Creates new form stock_medi
     */
    int c = interfazOwner.medi_control;

    public stock_medi() {
        initComponents();
        rell_tabla();
    }

    private void hab_des(boolean p) {
        btguar.setEnabled(p);
        im1.setEnabled(p);
        im2.setEnabled(p);
        im3.setEnabled(p);
        im4.setEnabled(p);
        im5.setEnabled(p);
        im6.setEnabled(p);
        btnue.setEnabled(!p);
    }

    private void guar() {
        interfazOwner.datos_medi[0][c] = im1.getText();
        interfazOwner.datos_medi[1][c] = im2.getText();
        interfazOwner.datos_medi[2][c] = im3.getText();
        interfazOwner.datos_medi[3][c] = im5.getText();
        interfazOwner.datos_medi2[0][c] = Integer.parseInt(im4.getText());
        interfazOwner.datos_medi2[1][c] = Integer.parseInt(im6.getText());
        im1.setText("");
        im2.setText("");
        im3.setText("");
        im4.setText("");
        im5.setText("");
        im6.setText("");
    }

    public void add_tabla(int x) {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();

        modelo.addRow(new Object[]{x + 1, interfazOwner.datos_medi[0][x],
            interfazOwner.datos_medi[1][x], interfazOwner.datos_medi[2][x],
            interfazOwner.datos_medi[3][x], interfazOwner.datos_medi2[0][x],
        interfazOwner.datos_medi2[1][x]});
    }

    public void rell_tabla() {
        for (int i = 0; i < c; i++) {
            add_tabla(i);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnue = new javax.swing.JButton();
        btguar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        im1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        im2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        im3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        im4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        im5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        im6 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txbusc = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(236, 242, 246));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(236, 242, 246));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(150, 185, 210)), "Resgistrar medicamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(44, 62, 80))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1370, 140));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(236, 242, 246));
        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        btnue.setBackground(new java.awt.Color(40, 110, 160));
        btnue.setForeground(new java.awt.Color(255, 255, 255));
        btnue.setText("Nuevo ingreso");
        btnue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnueActionPerformed(evt);
            }
        });
        jPanel3.add(btnue);

        btguar.setBackground(new java.awt.Color(40, 110, 160));
        btguar.setForeground(new java.awt.Color(255, 255, 255));
        btguar.setText("Guardar");
        btguar.setEnabled(false);
        btguar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btguarActionPerformed(evt);
            }
        });
        jPanel3.add(btguar);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(236, 242, 246));
        jPanel4.setLayout(new java.awt.GridLayout(3, 4));

        jLabel5.setBackground(new java.awt.Color(236, 242, 246));
        jLabel5.setForeground(new java.awt.Color(44, 62, 80));
        jLabel5.setText("Nombre");
        jPanel4.add(jLabel5);

        im1.setBackground(new java.awt.Color(236, 242, 246));
        im1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(150, 185, 210)));
        im1.setEnabled(false);
        jPanel4.add(im1);

        jLabel4.setBackground(new java.awt.Color(236, 242, 246));
        jLabel4.setForeground(new java.awt.Color(44, 62, 80));
        jLabel4.setText("Dosis");
        jPanel4.add(jLabel4);

        im2.setBackground(new java.awt.Color(236, 242, 246));
        im2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(150, 185, 210)));
        im2.setEnabled(false);
        jPanel4.add(im2);

        jLabel3.setBackground(new java.awt.Color(236, 242, 246));
        jLabel3.setForeground(new java.awt.Color(44, 62, 80));
        jLabel3.setText("Marca");
        jPanel4.add(jLabel3);

        im3.setBackground(new java.awt.Color(236, 242, 246));
        im3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(150, 185, 210)));
        im3.setEnabled(false);
        jPanel4.add(im3);

        jLabel2.setBackground(new java.awt.Color(236, 242, 246));
        jLabel2.setForeground(new java.awt.Color(44, 62, 80));
        jLabel2.setText("Cantidad");
        jPanel4.add(jLabel2);

        im4.setBackground(new java.awt.Color(236, 242, 246));
        im4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(150, 185, 210)));
        im4.setEnabled(false);
        im4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im4ActionPerformed(evt);
            }
        });
        jPanel4.add(im4);

        jLabel1.setBackground(new java.awt.Color(236, 242, 246));
        jLabel1.setForeground(new java.awt.Color(44, 62, 80));
        jLabel1.setText("Vencimiento lote");
        jPanel4.add(jLabel1);

        im5.setBackground(new java.awt.Color(236, 242, 246));
        im5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(150, 185, 210)));
        im5.setEnabled(false);
        im5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                im5ActionPerformed(evt);
            }
        });
        jPanel4.add(im5);

        jLabel6.setBackground(new java.awt.Color(236, 242, 246));
        jLabel6.setForeground(new java.awt.Color(44, 62, 80));
        jLabel6.setText("Alerta de stock mínimo");
        jPanel4.add(jLabel6);

        im6.setBackground(new java.awt.Color(236, 242, 246));
        im6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(150, 185, 210)));
        im6.setEnabled(false);
        jPanel4.add(im6);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel5.setBackground(new java.awt.Color(236, 242, 246));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(150, 185, 210)), "Inventario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(44, 62, 80))); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(462, 300));
        jPanel5.setLayout(new java.awt.GridLayout(1, 1));

        jScrollPane1.setBackground(new java.awt.Color(236, 242, 246));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(150, 185, 210)));
        jScrollPane1.setForeground(new java.awt.Color(44, 62, 80));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 340));

        tabla.setBackground(new java.awt.Color(236, 242, 246));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Dosis", "Marca", "Vencimineto", "Cantidad", "Alerta de stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        jPanel5.add(jScrollPane1);

        jPanel1.setBackground(new java.awt.Color(236, 242, 246));

        jLabel7.setForeground(new java.awt.Color(44, 62, 80));
        jLabel7.setText("Ingrese codigo para editar");
        jPanel1.add(jLabel7);
        jPanel1.add(jSeparator2);

        txbusc.setBackground(new java.awt.Color(236, 242, 246));
        txbusc.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(150, 185, 210)));
        txbusc.setPreferredSize(new java.awt.Dimension(100, 22));
        txbusc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbuscActionPerformed(evt);
            }
        });
        jPanel1.add(txbusc);

        jButton3.setBackground(new java.awt.Color(40, 110, 160));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Seleccionar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jPanel1.add(jSeparator3);
        jPanel1.add(jSeparator4);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(670, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Dosis", "Marca", "Vencimiento", "Cantidad", "Alerta de stock"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jPanel1.add(jScrollPane3);

        jButton2.setBackground(new java.awt.Color(40, 110, 160));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("EDITAR");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton1.setBackground(new java.awt.Color(40, 110, 160));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jPanel5.add(jPanel1);

        add(jPanel5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btguarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btguarActionPerformed
        guar();
        add_tabla(c);
        c++;
        interfazOwner.medi_control = c;
        hab_des(false);
    }//GEN-LAST:event_btguarActionPerformed

    private void im4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_im4ActionPerformed

    private void btnueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnueActionPerformed

        hab_des(true);
    }//GEN-LAST:event_btnueActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        interfazOwner principal = (interfazOwner) javax.swing.SwingUtilities.getWindowAncestor(this);
        principal.cambiarPanel(new botica_principal());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int x = Integer.parseInt(txbusc.getText()) - 1;

        DefaultTableModel modelo1 = (DefaultTableModel) jTable1.getModel();

        interfazOwner.datos_medi[0][x] = (String) modelo1.getValueAt(x, 1);
        interfazOwner.datos_medi[1][x] = (String) modelo1.getValueAt(x, 2);
        interfazOwner.datos_medi[2][x] = (String) modelo1.getValueAt(x, 3);
        interfazOwner.datos_medi[3][x] = (String) modelo1.getValueAt(x, 4);
        

        interfazOwner.datos_medi2[0][x]
                = Integer.parseInt(modelo1.getValueAt(x, 5).toString());

        interfazOwner.datos_medi2[1][x]
                = Integer.parseInt(modelo1.getValueAt(x, 6).toString());

        DefaultTableModel modelo2 = (DefaultTableModel) tabla.getModel();

        modelo2.setValueAt(interfazOwner.datos_medi[0][x], x, 1);
        modelo2.setValueAt(interfazOwner.datos_medi[1][x], x, 2);
        modelo2.setValueAt(interfazOwner.datos_medi[2][x], x, 3);
        modelo2.setValueAt(interfazOwner.datos_medi[3][x], x, 4);
        modelo2.setValueAt(interfazOwner.datos_medi2[0][x], x, 5);
        modelo2.setValueAt(interfazOwner.datos_medi2[1][x], x, 6);
        
       modelo1.setNumRows(0);
       jButton3.setEnabled(true);
       jButton2.setEnabled(false);
       txbusc.setText("");
       txbusc.setEnabled(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton2.setEnabled(true);
    
        int x = Integer.parseInt(txbusc.getText()) - 1;
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.addRow(new Object[]{x + 1, interfazOwner.datos_medi[0][x],
            interfazOwner.datos_medi[1][x], interfazOwner.datos_medi[2][x],
            interfazOwner.datos_medi[3][x], interfazOwner.datos_medi2[0][x],
            interfazOwner.datos_medi2[1][x]});

        jButton3.setEnabled(false);
        txbusc.setEnabled(false);


    }//GEN-LAST:event_jButton3ActionPerformed

    private void txbuscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbuscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbuscActionPerformed

    private void im5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_im5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_im5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btguar;
    private javax.swing.JButton btnue;
    private javax.swing.JTextField im1;
    private javax.swing.JTextField im2;
    private javax.swing.JTextField im3;
    private javax.swing.JTextField im4;
    private javax.swing.JTextField im5;
    private javax.swing.JTextField im6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    public static javax.swing.JTable tabla;
    private javax.swing.JTextField txbusc;
    // End of variables declaration//GEN-END:variables
}
